### ISSUE TITLE
Aspen - KV - Version, Gossip, and Recover by Batch

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#103]
The early versions of Aspen were written (quite naively) without batches or atomic transactions in mind. Each operation was processed and versioned on its own. Now that we have basic locally atomic batches, parts of the key-value layer have been altered to process batches instead of individual requests, while others (such as the recovery transform and version assigner) still process on a per request basis. 

I'd like tall components to handle batched operations. This should help increase simplicity and improve efficiency over the long run. However, this will require some careful thinking around versioning batches properly (especially in the context of failure recovery and key-value state propagation).

**Comment by zeina1i** [comment]
Hey @emilbon99 
What do you mean by "tall components"?
