### ISSUE TITLE
Aspen - KV - State Forwarding

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#104]
This issue is critical for resilient multi-node operation. 

### Bug Description

Imaging we have a cluster with nodes A(1) and B(2). If Node B(2) fails, A(1) is allowed to continue serving all reads as well as writes to its own lease. When B(2) comes back online, it may have missed out on gossiped operations that Node A(1) has already recovered. We've reached indefinite inconsistency, which is not good.

### General Solution

We need to design a mechanism for which we can gracefully recover from failures by propagating unreceived key-value operations to a restarted node. I outlined basic ideas for accomplishing this in [the original Aspen RFC](https://docs.synnaxlabs.com/rfc/2-220518-aspen-distributed-storage#5---failure-recovery). The  challenge here is not only syncing key-value state after a failure, but also thinking more generally about how a Synnax node should recover from a state of indefinite inconsistency. For example, when should aspen start allowing reads and writes during the recovery process?

**Comment by zeina1i** [comment]
Hey @emilbon99 
Does aspen tasks have an specific order?
If not, Can I take this one?

It's my first attempt on a distributed system. So if you have any suggestion about reading an specific reference etc. I would appreciate that.

**Comment by zeina1i** [comment]
@emilbon99 
Bytheway the descriptions in the rfc file about recovery is very useful and I think can be a great entrypoint for me :)

**Comment by emilbon99** [comment]
@zeina1i This is a great one to start on. I'm by no means an expert on distributed systems, so the logic in that RFC may be flawed in some critical manner. 

That being said, I gave it another glance and it seems sound except for one change. It should be the patient node's job to request operation forwarding from each leaseholder in the cluster, instead of relying on the failure detection algorithm to automatically forward. Whenever the generation of the node is incremented, it should go into failure recovery node and start requesting updated KV operations from other nodes.

There is one fundamental flaw here that I can think of off the top of my head, and that is dealing with unpropagated, recovered operations during network partitions. Getting past this is going to require implementing #107 and designing a more advanced recovery algorithm.

In terms of resources, the book I always go back to is [Distributed Systems](https://www.amazon.com/Distributed-Systems-Maarten-van-Steen/dp/9081540637/ref=sr_1_1?keywords=distributed+systems+maarten+van+steen&qid=1680130854&sr=8-1) by Martin Van Steen. It doesn't go into much detail regarding Gossip Algorithms, but it does provide a good high level overview of how and why they are used as well as some common pitfalls. I have the print version, but you might be able to find a PDF online for free (not that I'm recommending that ;)).

[This](https://medium.com/@swarnimsinghal/implementing-cassandras-gossip-protocol-part-1-b9fd161e5f49) is an interesting medium article that implements a basic version of the gossip algorithm used in Cassandra, and is good for a practical introduction. It is missing a lot of the more advanced (and necessary) implementation details for a production-ready gossip network.

In terms of actual implementations, the two that I frequently reference are the [Cassandra](https://github.com/apache/cassandra/tree/549bf38a073e9b467b1f95223ed0c05f2496c40a/src/java/org/apache/cassandra/gms) algorithm and the [CockroachDB](https://github.com/cockroachdb/cockroach/tree/master/pkg/gossip) one.

The Cassandra one shares more similarities to Aspen than the Cockroach one, but the Cockroach one is written in go, which is always nice.j

Lastly, there's also [Serf](https://github.com/hashicorp/serf) which is the hashicorp implementation based on [SWIM](https://www.cs.cornell.edu/projects/Quicksilver/public_pdfs/SWIM.pdf).

It's important to remember that the current Aspen implementation is very rudimentary (I built it to prove the concept is possible), so be wary of trusting the code.

As you explore these algorithms and read the reference, let me know if you have any questions and we can brainstorm the technical solution to this issue.

**Comment by zeina1i** [comment]
@emilbon99 thanks for complete description.
I read the references, and keep you updated.

**Comment by emilbon99** [comment]
Sounds good. It might also be worth it to implement #103 in conjunction with or before this issue.

**Comment by emilbon99** [comment]
@zeina1i Just checking in. How's it going on this?

**Comment by zeina1i** [comment]
Hey @emilbon99 
Unfortunately due to my personal daily job, the speed was not fast enough. I try to give it more priority, and update you here from now on.
