### ISSUE TITLE
Server - Configure Homebrew Tap

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#229]
I'd like to make a homebrew tap for Synnax that makes it easy to install. This issue should probably be expanded to include `apt` and `chocolatey` as well. Low priority, good first issue.

**Comment by MatchaOnMuffins** [comment]
I made an initial homebrew tap for synnax under my own [account](https://github.com/MatchaOnMuffins/homebrew-synnax)
Now, synnax can be installed via the following commands:

brew tap MatchaOnMuffins synnax
brew install synnax

If everything looks good, can someone create a repository named homebrew-synnax under the synnax-labs organization?

**Comment by emilbon99** [comment]
Is there a way we can get this to always have the latest version without needing to update manually? Perhaps query the github API somehow? Or add a new CI action?

**Comment by MatchaOnMuffins** [comment]
yup, something like this should work:
https://github.com/dawidd6/action-homebrew-bump-formula
