### ISSUE TITLE
Delta - Moving Average Lines

### ISSUE THREAD

**Issue by pjdotson** [synnaxlabs/synnax#232]
Add a feature for thermocouple readings to subtract thermocouple readings from the ambient thermocouple so we see the temperature delta

**Comment by emilbon99** [comment]
Tracking support for the [Offscreen Canvas API](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) on WebKit. It's experimental right now. Will begin implementing this along with a larger plot refactor when Apple moves it to the stable build.

**Comment by emilbon99** [comment]
This was completed in #230
