### ISSUE TITLE
Add P&ID Relief Valve

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#284]
Design the symbol for the element in Figma, export it as an SVG, and create the component in Pluto.

<sub>From [SyncLinear.com](https://synclinear.com) | [SY-124](https://linear.app/synnaxlabs/issue/SY-124/add-pandid-relief-valve)</sub>

**Comment by am3005** [comment]
path: file inside pluto -> src -> vis -> regulator: (copy what happened with regulator with relief valve, make relief valve file inside vis valve folder, reliefvalvefile.tsx
