### ISSUE TITLE
Freighter - C++ Implementation

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#343]
We're starting work on the Synnax client library in C++, and, to implement it, we first need to set up all of the networking infrastructure to communicate with the Synnax database.

Freighter was designed as a way to separate the implementation details of specific network protocols such as gRPC and HTTP away from the libraries that consume them. The RFC and protocol behavior definition loosely mimics that of gRPC, and is described in detail in this [RFC.](https://github.com/synnaxlabs/synnax/blob/main/docs/tech/rfc/0006-220809-freighter.md)

In code, freighter is essentially a lightweight adapter shim that converts the function/method calls of the standard interface it exposes to those of the underlying network implementation. We already have three implementations in typescript (`freighter/ts`), python (`freighter/py`) and go (`freighter/go`).  

The outline for implementing freighter in C++ is as follows (note that I'm not an expert C++ programmer, so I might get some of the details wrong):

**An important note**: freighter defines interfaces for both the client and server side. For the C++ implementation, we only need to define and implement implement the **client** side interfaces. 

1. Create a new directory inside `freighter` titled `cpp`.
2. Configure a C++ project in that directory that can easily be built as a consumable library (use your judgement as to the best method for doing so).
3. Implement the `unary` and `streaming` protocols as abstract base classes (these should be public to library consumers). Along with the signature outlined in the RFC, there are reference definitions available in the following places:
   1. Go definition of unary interface: [https://github.com/synnaxlabs/synnax/blob/main/freighter/go/unary.go](https://github.com/synnaxlabs/synnax/blob/main/freighter/go/unary.go)
   2. Go definition of streaming interface: [https://github.com/synnaxlabs/synnax/blob/main/freighter/go/stream.go](https://github.com/synnaxlabs/synnax/blob/main/freighter/go/stream.go)
   3. Typescript definition for unary client: [https://github.com/synnaxlabs/synnax/blob/main/freighter/ts/src/unary.ts](https://github.com/synnaxlabs/synnax/blob/main/freighter/ts/src/unary.ts)
   4. Typescript definition for streaming client: [https://github.com/synnaxlabs/synnax/blob/main/freighter/ts/src/stream.ts](https://github.com/synnaxlabs/synnax/blob/main/freighter/ts/src/stream.ts).
   5. Python definition for streaming client: [https://github.com/synnaxlabs/synnax/blob/main/freighter/py/freighter/stream.py](https://github.com/synnaxlabs/synnax/blob/main/freighter/py/freighter/stream.py)
   6. Python definition for unary client: 

      [https://github.com/synnaxlabs/synnax/blob/main/freighter/py/freighter/unary.py](https://github.com/synnaxlabs/synnax/blob/main/freighter/py/freighter/unary.py)

      Note how only the go implementation has definitions for the server side interfaces. Like typescript and python, our C++ implementation only needs to define the client side interfaces at the moment.
4. Implement an adapter to the freighter protocol using the gRPC C++ libraries. We'll probably need to talk in more detail about how to do this. I had to do a few funky things when building the gRPC adapter for go (source is [https://github.com/synnaxlabs/synnax/tree/main/freighter/go/fgrpc](https://github.com/synnaxlabs/synnax/tree/main/freighter/go/fgrpc)). This implementation should not require building or reading any generated proto files, and should leave that to the consumer.
5. Write tests! We have an integration testing server that you can test against: [https://github.com/synnaxlabs/synnax/tree/main/freighter/integration](https://github.com/synnaxlabs/synnax/tree/main/freighter/integration). I still need to add gRPC support here, and should have it ready once you get to this step. Link to that issue is here: [https://linear.app/synnaxlabs/issue/SY-181/freighter-integration-testing-server-grpc-support](https://linear.app/synnaxlabs/issue/SY-181/freighter-integration-testing-server-grpc-support).

<sub>From [SyncLinear.com](https://synclinear.com) | [SY-178](https://linear.app/synnaxlabs/issue/SY-178/freighter-c-implementation)</sub>

<sub>[SY-182](https://linear.app/synnaxlabs/issue/SY-182/[sy-178]-freighter-c-implementation)</sub>

**Comment by sverlon** [comment]
What are we defining as 'consumable' here? Used within C++, or something that we can write as a binding for other languages?

**Comment by sverlon** [comment]
Link to some notetaking: https://docs.google.com/document/d/1RXD1S9vDx4juos3qDGel7UKLVbuzhw1k5GsIahLV0pY/edit?usp=sharing

**Comment by sverlon** [comment]
As of Sept. 18 2023:

- Set up build environment using bazel, set up to (mostly) compile and build the whole library with one command
- Wasn't able to compile .proto grpc services within bazel, but no biggy, can just build the .proto files separately and then link them as `cpp_binary`.

**Comment by sverlon** [comment]
As of Sept. 24 2023

- Unary side of gRPC library mostly complete, only need to deal with edge case of switching targets mid rpc
- Testing suffices for single target with error handling
