### ISSUE TITLE
Read instrumentation information from excel/sheets

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#353]
It's common to store channel specifications in excel or google sheets. These excel sheets typically store the following parameters:

1. Channel name
2. Channel device
3. Channel data type
4. Channel units
5. Port #
6. Calibration

We'd like to have a python tool that allows our users to leverage their instrumentation sheet as the single source of truth for the instrumentation configuration. 

The steps for the successful completion of this ticket are as follows:

1. Build a polymorphic class (or set of classes) constructed using a file path or URL that automatically determines whether the file is an excel sheet or a google sheet and provides the caller with an interface for reading data from it.
2. Define a standard format for a spreadsheet. This will require talking to the important stakeholders whose job it will be to maintain these sheets. If you're feeling particularly talented, see If it's possible to introspect the layout of a sheet and automatically determine the format.
3. Create a set of functions/classes that parse the format in the spreadsheet and define any necessary channels within Synnax server (i.e. channels that don't exist should be created). 
4. Create another set of functions that read the calibration information for the relevant set of channels and write it to a calibration channel.

We'll talk about steps  3 and 4 in detail when you get there.

<sub>[SY-188](https://linear.app/synnaxlabs/issue/SY-188/read-channel-information-from-excelsheets)</sub>

**Comment by evanhekman** [comment]
/
