### ISSUE TITLE
[SY-193] Freighter - C++ - Streaming Implementation

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#365]
null

<sub>[SY-193](https://linear.app/synnaxlabs/issue/SY-193/freighter-c-streaming-implementation)</sub>

**Comment by sverlon** [comment]
Things to clean up: 

- gRPC streamer checks to see if there is a last context or stub even though it is not needed... why did I write this
- Internal error types
- More to come, will look at this

**Comment by emilbon99** [comment]
@sverlon can I close this?

**Comment by sverlon** [comment]
Closing — moving above to[ ](https://github.com/synnaxlabs/synnax/issues/401)

**Comment by sverlon** [comment]
Closing — moving above to [ Client - C++ - Channel Service Implementation](https://github.com/synnaxlabs/synnax/issues/401)
