### ISSUE TITLE
Cesium - Properly Implement Data File Size Limits

### ISSUE THREAD

**Issue by emilbon99** [synnaxlabs/synnax#85]
The cesium ranger file controller doesn't acknowledge soft file size limits at the moment and continues to write to oversized files in its registry. We need to update the file controller to respect these limits and rotate data files accordingly.

**Comment by LeonLiur** [comment]
Is this Issue still relevant? I implemented a file size checker in the refactored file controller so acquiring new writers won't be to oversize files. If needed I can look into how to stop existing writers from writing once a limit is reached
